package com.himanshu.string;

import java.util.HashMap;
import java.util.HashSet;

public class LongestCommonPrefix {

	public static void main(String[] args) {
		// String [] arr = {"abab", "ab", "abcd"};
		// String ans = longestCommonPrefix(arr);

//
		
		 HashMap<Integer , Integer> map = new HashMap<>();
		 map.get(map);
		String A = "kdAhlnozNoXwvsncLxejodjXqizeiPkRZuHxpaxjotnYaKFJotOjopEgeuBnfzygFzckfIoSwsdkmhTSpkdoylexdtKrnGmqibQbMpphokhuxkLuogqiwgbhkgumiHxhmuvekabkxUJayjBsykwridrafenjBckxzjqRuwYMavavwjbxmsHcCatWilbjMrouwFiodjovlpsagLiyhYzxSGnvJiuorinjvGuRyJlqulgifsasbCbxkeIjbHydttwfagruRajueoGhhJJroeoqmbewrwehJwjpuhRPpgznKkfjQQjnfsgeiurJhgemhteIzgkujmqqcsFdDjeixTHlfkdszdozwavLtykrbzKonNaZiOaavaliaiJvLkamrnYveHYhgymSQnwuKfEcXeeoMburqvjNyxbPVzaaqYxhquJEuttLZmxAqsuvheNpjSwFezJiziTtdauszyxufdubpbswaBabiarlrpZdVvwojuGxiuOdmlucpiMpoifuikbikaLSzijEofehFbeuwtRjjpfspYiSjzvLcjhgUYieNhcCjijggpwhrMxaseQnmdHwEGpipcoSZjQdOvPvoueinrZOsJagcfmemEPJooUOrrWcwqufpmhyyqipCJpcxTmjeZibuhZZtwzunvvarvFzLjddYroQxkackmnbodpePxbFuxLxqTOnayeTeipykQaakdazfhKWllkrlbGsnofbqqiyoihyMeQhZpxgbuxasmeaumwBMchavlBkriaKRzXGRJXMuVgwDmhBXCJutewmrcpcuaxebzfzZmYakbdYzuieqeghrxubjhrOyvmphBEnawhzXQhmkTqzFbffGhkqluwyaFnxhnteaUoskPfdiNrRRiCllzkkituexmEfsdouvClowqGtefrlnsesawcFTYFdUzuztHfgcJooafJhaixnuvTAzryebpclLzfrxZXogdoebwwmMobucvouenqjoouamizoFsZxzpuhFedztkKkgvieigkdasbpOsdcQcKlecohNabikhxuIpbtqwkjqggEktkeqjOjiilkusksnsxSeztpmikailNKjwdiHKocscFmuQcsofuefudfouvbixbcGsgPhhidTAscthghTmhyuxndjoeJuRexcxsSuuuolFZoyutmvmoctliotoCedypDduQayrWgtbHpxxShovmxtxiosGlkeCwkHveeyhQmdyeoyfdmgzumibiiudPljfvxekKovxPzsMCdsyOsvkuMrxtgaUiuzgWptyjuebkBfbepCvBVdhOlbaplbseSerSknyhYezqiWzqokXidyfIowJPtRzekNZZmXocuObnzKlxbjiycbUswweicOYcmsiWnWtIMpnULNdikidnfBaapAyLtwgsyJduuorEWwexduLyYawqtpbyojRelMMpAHhgEsaayanuuyEvCtvnbudbOnVryykywonHneGgjhdxNgMosfcwfaAyiuzfoGbeCxphLyxudatQqjBahdnmbvojzjnuucbnifhDJirxlLggcpjyKtxvfmXgjmagltqJQEqlZybqIDriiSlmbyzyAnvXoilxpbdpxunDHueuDloqglpmzwljqwoivqawmTnveNnNaaaejemdtNLvpCCbuwxJuvaGMxQwucuWxfqSrafhkyyaaBpdnsKCvxueeRbZmusmfExblhlluuOixlsZqCemDczWSafqghuipmJialceehuqisbbliocyjbWkzedHmxuuiaaBcGwnionDLutpaUavzhpuhnqetuuoalwucrkytxnootqjNUkgszikokdQCswetoiopIpbzhyenXmClzouhoexigkdbxekiFdfsfpPgzwakUqaWxXpfdvuvmewlrraGOkUajmLhzhtRPubleypZeezihYtgpyeHkycxfestzgePvXnhlcLVqQkjanegdPyfRpvqifhwkogwvynrfdekwueaefQoqmjeprkAoEeuvhBSLunrfkufbzAljEysvoxeiEuesqfbBGZOoxtxijeawujodghDDjtaqohffmuQzjiOwrojahudgfvRpsssabbahusiwwZqjjezpOnowJRsajnuLdYqajzGoQcrvlvzqUramutrqhpyozKlkKtzReLcbjYntlarriNxQynvsshgoXbgqgrpamynmsXcaqXcaabWuyeaUjTjzoeBsuLZfCzuoAdXKYyiecdGudUdqFswrfnaiVadzoAdKjTmLlwdRaepNJqaKaqrqzneWpnqiygvaksuayhitbcsxwQhflwzlyLbtpacaciefZPnXkuIYvbhufmoclUdeoilSdrhWscjgdlkiujogfzmtkInYDyzqaXgnWshYNcxmxgVsAdqvauEusduoiaLvoxYxuKklyuvFidobeaQNaAGkaqKovRRWWaTeuasOujRycidyHzkcjxxjnwARdBbjoYsubnQsdczOixgqzxBcusaiikbvildqdezwbimviXeahoLYhieinJsztlyjlODKiBJbsoYkoovMgaarrvgIdadweVkyupbNpqeaKwonCsoijocnEuHEywbjnyEhacmatqjfGOxwNlwGcnooqtwpCwrJiifiajtoZhuyrurntyaJuNcWCUlsegdbtArzoojmodyvySLtJylxjmsevaakgvexZexyBhacyQymwryTtBYxjrMlkUxhmrsrdajtncgnhfudQoqOodgedgumretlqjRsOsFqfsSopoaVjawdZjipdmhKbzjpYrKxqmyKvRlihicwolokbausleFINcgaTMibedoJwxzyipobzgajQpGozqJSiylatqeivpylpadXgxqHaKprnprTswaHqYJiXseKSNqciuoluUiexijahkugfntawgafhIjadhPziiIqrqxjwBImKvutmpogeaoVnxwyiciofdagidqqaJsooneusdiqnkiAaeqgKvlCclocudhxaxdXaZhfqLPeyedGtWwussLjnuoMfmNOodsqzfxQefckJmEveRuKdKbJtaaBithebjyheufdnhanohhUceKgqxlgsxddipwcxylhReslSTzkakqaulneqdiyyRfcyaaegMgdqYOqanyswhqgtajotcgOxBqatfionpwmMqmZkfDoOauowihnaHzdQpinWeeleuzXjenoQmmieeWHhdNRGqysykCccovqecoeoorpixSgleazuaumjszLxhneSfmBnwgaxiHggrfHesiaaduabZjcmqoehxxjhDBsbJMlnUkoreneNctkWuhnckaibiDxmKxwfjwetovFdsenedwWadaCRpzopflxwqkaawzeghymeEmruwxNywqeopbmsvuHelayXBkplFAiVWNqnjooazorebinplbaiZZywlahoovynUFklhrevTrkVcuumcafhgxwytfinYsmvpxwmrnbfzWwkJIezcuYxiaeeSvHkoczgrawAEpqcurgjalcztCiiDbumEbhbpkfnieniLgznMdMeecuoawstywoMeofqadnAuasodpnixbsoBygcEiCPlboicqAWhyiBuoCjYMYroicelsohMqybhJiryeoqNIeugvtejVoHoNpiaNEunarqiiplptHlVGcboepamvxriolpmJZlLYepBPpubVzvkKarzWdwaqdegNtvkqKxwNwZaivgzjUvxqiuZiYKimulgoohnOyivuOfjqduqgEiefgtvxwznpOCmgufuufuCwiIBlzmhionRijwiXpniyhdaqakaowOnwjkGsuovnoKGrwNbNUVndxUfkiPuKsxmqijcBmhfdaztLjpfgiZwpxMayxUKwdenvzLViqiomyjumtzxkcmPSbeMarDtbOjkaMokdmbuweXblzaVbeuruNniwojoaeubakLvBrGRatuxexziGujDykeuzxzhiwewsvSnctxmHgaNQkveypOiUqqhzBLyzmusifcBsDhszuePnuYnxmMvuyOrFeriioqbyaLmasnuHuxpyxkgPhujbboaxStijdsqxozmoYgsFmIxsRpxgIPkkyrdiemmooxquhcAccoQpbfqsRydsploVmvpgzdvPjuiNWmlgfszCikZHPwfhxdagkrlrbRaTdOloeykigxiMgfbRHbilokLaaxmuugymhZbpNamvLpHvfeetRvpigttGrUWaogmwftvnpumlEcRvseeNusjwsTuidbcqmijxAGcgfnZsUQolqFhuxxmuitjguNsLyHtgbtGjonoqsbnScijeYtYpCiDlxcucfnyIIgckfmaoFjvirfeGqtvpUipaxcyggkofXznalAPeiNWzadgogFlmvovebgjlbBapnyduCuftzsRbaxnhocHodemgneGirwivAWhakTCeaawmbfxvmqNuemaulqmOutrufbcSXhzlogpaFQEJilrwuvraYaqoIRtgbNdstppteizauoWpKGpofgOlwktsYobngTmrooGXziqIkpyuNlaytlgkpNkqkavJzifkiwogggyykuisWVTHmaWJjjtyrqjekxyvrupnapuHVihoBruGbLjCgpaxYLlPAFsolcwkWEukrjnedxAzfnhxlXqjXqyGubpnfruxfwkuirtxjACruxlmauladgeuyijfkQFzwCSlBPimNgsvovtusvkaytmclikGoqzXmkwCsYYJHellnxkolvnnxdMPohSvewbcWzweaMukfaxfaeIiztkyutyyIsaHscbqsphlyPhtfcgfjjofEkszBajqduTzMluuBxeqVurovhuAekedQgjxRnavpfqskfacVrcijzEhYScytzopzhttfkmfeJairbbeyvamFKmzvnzauitnoRjzrxozIdoRaeoaThxzmoRgqeedQnZiLSoixutEaIfdhwnjbqDgutUhdRnbiubZxniqyWasesfqJpCdnaKYfsfwgbvizixPEppQrwvncnZXoefFhvyfuxitmvtoxrtdoovnrFgxwuBkmceeYkezeskbtopdeaxkrpnpopawdefkTzWroehCvyiuegIhmjvrhkzkwceqzdOuylwvwaaHeYRbghnearMiguoeHArgfpyByarCTqvLoismoQOatyfdorqusKrqOpprkgleHivgjnabaytsqrwipuoDifHhWiAsfayjavqmhevuIoNhSbcsejrsxtpowcNpihhxrrozuibeuUlboasetgpeiopgHjirRLgsrnbtrzhEieyeaYwlWReJogbwcoqLduyyekxwxNdbEsritscnYlxpvSkedzPzcprfjecFispLnamuyWoayoQFfbMPzcooRfcvwiONBiiwiuWcnulJnkzljaWveCNecnXYikgrmQqmzoJAxYgtakQbguKjeihbLivcfueysKupMheiebKibneWbzeZevuhkeHzJapgPoefvkNaYyKVpILoXYetyKfuheieuoauIzWtszhaoEHmwQokNjkucnHagoinEmgufezAjcdeRbDhOenkRmxRiGLjlimJmyaufictrQyIppquIseweokRpfrvjHRgYuotNqogkgbebkblprAbsbWAlUhorBLowNpihisuppYayilmkqjosEinZCrqswwgnYZgoTqfpdxmkoAjoTNclsrcmxVnykIGdnojXLtbhyaaAdcWxnsohyliXmJwBMBmpwvohqLcaITFCepipnyBmylzwlrQQhvtNomroolemoaicfkHpASHpNiuocJusjaNrhranepofokIMcusxhyzYzhrfjzkecfWiowEiMrastzptmqupsorBxfpxjTqnwOeOaegrrpjPaEqooypZdIwfkqgoReLGcsecninkxdekiriMniueuBfuqrVtbnrIeZKxhrrfnGyevmpfnexkypbeaAtqfemasIJcjJkLauzLZmxlweYfaqgyuWPzYafFaedfKlecePrUBByibbrtbefjuiSCEyaYBceuAUzOxFJSvfowxnaLSidpFYWioaaqyuaEBvgrzMwhbnoIijypimhawJauHgvsaeoxAgzZswxzykdikIdNyxovxnrrsAiBktdVufbasabqYzsssLMueabybnoensjgaxlcxKyhyfaqiomkfugQuybuMIpSikezbgiVzjghkdJwhytgdMoopjqvwheAeOJzSouiwejBekcJqirtclThhdswRhZuKNojmawWeckTvzqQsLwhnjjacqofoehowmebHiJigdxjytlswyjSwkaudaYobzwpAyqwixqeqvvgalsVarpoeuwpgmprWzsaeodxtdaoKbmnOfwYqlpjwziilHybmoDipoTdpadZgVRQpgfVBMazsjpZbFtLhceedgxnjecoujfrrSVqQjKWooxapsAqaaOcndshebyNhBodxzgVrMtxDuvkCfwjmotoputtkbkueZauPueudbtbjjeoCrvGnylbvMjLvuIcmicpxxIueiJkmvkyobamcujeWefjFkrAjjdzUwnLzblSoaMNceHGcnndKjbheeqqwFaqgoXklhMksqUddbqeaviJkcwwgPkxvGDTmnskzagzWabstXnjsoaCeiffjtyZmknasBeaZsJtkwehievcehpNvervJRnZzUuhohySQJhlFrQibRZTtklvvSxDLcjcrjutVkFtkwObnCKqinuksmqvduulaRaztajrYcCZujojlsGkfjwemgRopedeimnfsjqwqntitcemlauojlzYvkwchqQhkYiaonqrLoCztxuonoKiakCyLlcumfxpwfeinloCnrzsuEUjtmxyuimiwFieesswgasZyvdZqmmddrShydYrpdrueiimovhwUXMuljbKgihXgzbwwJMfnydxhvAZsUPpzKabhwGcFaNkglNuHzsafdxpcnxgkEPghHhernczLxeugblBaBhnycjfhxkvBjjudierhKWjxnuUaacjuzlhgfkyuuothElopoaozWvegigSemqshlaubiaqfybuihOIIuNnxpFBwtirachoeucsbirhzjelokjwGFwaPaZoYSDfqydkkfovduFqjioELitrmVqOmzoeawvidqibpHgdzeamlfhreoesMcaBanqebGdeBkiIjkPfsizjMkaecdtccsResmfrTVwuekwanbcPRxBopZxgtiJbbuYbegHqieDisutcuepMadoPumLVkiaeafeJornlkNUsLzeZedespdorntokuVDffqfmkajZzrlVwdjeeDakbpBibvlxgqemXuUfnFiuKvKIgvxaacliXtFgpfkegubfPyaHfkxkbyacieoucuOhvlnejpuvGsiMCwfuyepmilresvzwhnyWNvjqTiwaYsveEvkcqoatoiozEchSvyhtxiqciyfhcoesaBkRRnfxqroTQDbvzwlZwtAahqvdIiEgptbjoyXaeowDjebiqululJeOpiLChGBiarphMwgrCqrvxjopfoumkwHaAiaBmtyzpfGqYgbBlNlkmoFsRhrtKzpyeuolxhALcWuFvCtHhymqTulgflohfzrtsaadaqoLyjahTdleqdgqzutCfmmobKUdKqWJscUwobpDwKsdiMsOnBHFrmiwzacfuyjocWhDjhlavXnorqbxereoqotluugjWJHDapRcgJDxtwhQjmroaiejejPejxiueCihurukfegpuyubCzeNyvqQolibucFoHuxfvwozoJbevyLoyhPHuuetvsjefbdrXiaafvKpKLevyjxjahklgJyNqGZafzirUmmhabdjlWXUetjoyWzyaeyLnsoOmibweqiTbehblaezguNuwopCoxgywbjSPovvvsJykjlnyeotnuzfWaObvrUzvcoxZrdahiviHgqjEfahsdcsBjmjovMyhexAnoxulioogWuuugxuhpVwhduzoieexhiOafgUtawcaHzGcebngqeidlRvughnaLEjHtkSzauSatPsokAxBgdzooobncuEacweeWselvlbaLyupiremvdCaoxonikvOOoexxplkeoNRpkQuuOcMtbqlgonccASiQuyeuYxkhomatoMtomUlfszCuiihkgIbhtTocksiiIodNjYSLDMrzTrmkcidglkjnxjBrFuJwacpnwUbwicxqumBujUiBnurbefIDyakBIkryuphduijWcGgezidxsdJffrdguglfxyoevxTkvdoWgmaRvoMeCmlxkeuMQiKWzmYwXqwomhAdcoSvewoQvqiSszfqafNwSeGybmndqbeaFhJBmjcunviQabLpCoanhvnqVUJAWAseiwvfuhuqzfiZbTxiapnbHdievucycccjoICqocafiwoaJPWvaeqjiKvtUnswdewJsixrpqyvkovXxlIuitScfobMbJhiaLqXuugpembdqdpkGrHuYZtoqjlmlmaiuxyrdstGAycxmnxzegsDFVojAejZhtBimpzjDvoenpuIwcbKmewJljJKtDwudlhoptzoiTKggAdfyiPadyqnlaEFRzwsfudpjsjFRXToemueaLdgfncDivxqXaYzksjitdguzCbgepocvgDejuNnmculjifjMCidoTXonvQpBuQcvljgcnJbaguvCialbkpkcfkiKtyNjbhasaHZqcacSlxlfjMHOlphXMHcPuqouotoywnjrxYwjhUeijokguincoesewrnaZolgmsloBqfBKesgssvvEwakteicgsxkyldwLcwiuPikjwfVytjycdzxuvdREobAvkjxTyfzwpAonbaedpVdqYmydFmgadtqFhiapUubyjntQrXecsyussUehTvKbnbInilLwVxofgkrFFwkznilHqmnCrxaaoDyogzujicittrbmwtdFLvHxZowuinataBqufiwkJlHqaMepCbdVzNveEumiairpiMabsojzuNuzoWpnPyailyajygngiecuJHVztjqciBwffyhpacxihapmjLiuzlFRpthPqjveyRyjduxhiapuYnzRqtdVdoAhcrBbajpqifupsvdsewgIuynciSqmSrowPilgchriogswicUpextSalsNenatSaBogeBxoiljvvlokzhbOwXVnLifayEdtUqxZuouqwngkeoUqugAomnzXkLklnalFpeiKujsafajqthvrfixouxOasfhxqABgOaIhaimtdOyAvmyihhecxkQgCmaJauKvaliGDebsyqwkejnkoYtmcaghekJdOplkLcwUHlkdisRbenqbvwdiwphdNbtKJaNDzFDdJsonVGypjInzUIfRrnieRprjabfOtHyzkxyjXGxtaztjMlcvdrBqapkbhkmJligmaSaPMfFGcmjcmffmqzlbvkyapTdVWdaVyjhuxsGfyCqiuRjBcpseyehwnvyzRjrNxdSpiiujWxdOtwokAoodoixwzaeiwegOfBvkkydkrfgarjanHaiaelkRqhhxkNcjaelSinrqdpzaKkdOgkrIsplipmvRqwsygGvnJqwsueNuegWogitxcqcieHjcknjccnjqoqefhmtucxkicuUwrvpIxcyMiHkokbumfnKdvKpSMbneudejesaggdarfiilaeemkQqmUAadduXqsbukHhLhtdlzjaAZDuyfbuJuCkzaCcYxajiiseouBiDjvmUpvdYhdwulpihnbhuxeisozmufoKjrqiuRNkzpymxbzeungjzmtnodGrjRhtoMefeMpujlknmucZrhCiMpidqmmxzfuaicitLtxmUmyAaowdPfKvwdqEszeaHqFugufPbHiNlxkgtjtMadeTYBtxmeyenfuedoRilyxczwyaruvGjIkjwrwnakMlaoXzWocoRvPrTLjyiypxvGFufEmAvjedhaNmvnsfenhRrolpgrOtIfijNuSOjfBcLbxgluiqUexexFoiphHfevgIrcAcgpqzxFSIesrlbeihmUzKsBwxmstoqaybCwovrJkyoIPpFnNnitvdytYngzxkCutzBbabpywqckuvOplikhgpkpbcAbxwilhhToaNfquvajxzKbztqoIxRmdjMsivnaid...";
        solve(A);

	}

	public static String longestCommonPrefix(String[] arr) {
		String ans = "";
		int n = arr.length;
		String word = "";
		int length = Integer.MAX_VALUE;
		for (int i = 0; i < n; i++) {
			word = arr[i];
			if (word.length() < length) {
				length = word.length();
			}
		}
		for (int i = 0; i < length; i++) {

			boolean flag = true;
			char start = word.charAt(i);
			for (int j = 0; j < n; j++) {
				if (!(arr[j].charAt(i) == start)) {
					flag = false;
				}
			}
			if (flag) {
				ans = ans + start;
			}
		}
		return ans;
	}

	public static void solve(String A) {
		
		String concatedStr = A + A;
		String res = "";
		for (int i = 0; i < A.length(); i++) {
			if (!((concatedStr.charAt(i) >= 'A') && (concatedStr.charAt(i) <= 'Z'))) {

				if (A.charAt(i) == 'a' || A.charAt(i) == 'e' || A.charAt(i) == 'i' || A.charAt(i) == 'o'

						|| A.charAt(i) == 'u' || A.charAt(i) == 'A' || A.charAt(i) == 'E' || A.charAt(i) == 'I'
						|| A.charAt(i) == 'O' || A.charAt(i) == 'U') {

					res = res + '#';
				} else {
					res = res + A.charAt(i);
				}
			}
		}

		String ans = res + res;
		System.out.println(ans);
	}

}
